### ISSUE TITLE
Background color (not fixed ?)

### ISSUE THREAD

**Issue by Stefdv** [kinimesi/cytoscape-svg#6] opened 2021-01-20 13:22 UTC

**Comment by Stefdv** [comment] 2021-01-20 13:24
It seems that the background color (option bg) is not working. i get a persistent yellow background

**Comment by Stefdv** [comment] 2021-01-20 13:48
I should add that i'm using cytoscape-svg.js in browser

**Comment by kinimesi** [comment] 2021-01-27 06:52
Are you sure? I just tested the demo file and it works. Below is the syntax. You need to pass the background color code as an argument. The default color in the demo file is yellow.

```js
cy.svg({scale: 1, full: true, bg: '#ff0000'})
```

**Comment by Stefdv** [comment] 2021-01-30 14:28
That's how i did it... will try again. Tx for the reply

**Comment by kinimesi** [comment] 2021-04-03 10:39
Closing since I can't reproduce. Please reopen and provide an example if the issue still exists.

**Closed as completed by kinimesi** 2021-04-03 10:39 UTC
